name: System tests
on:
  workflow_dispatch:
    inputs:
      frontendVersion:
        description: 'Frontend version'
        required: true
      backendVersion:
        description: 'Backend version'
        required: true

jobs:
  system-tests:
    runs-on: ubuntu-latest
    env:
      FRONTEND_VERSION: ${{ github.event.inputs.frontendVersion }}
      BACKEND_VERSION: ${{ github.event.inputs.backendVersion }}
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
    strategy:
      matrix:
#        browser: [ chrome, firefox, edge ]
        browser: [ chrome ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start Docker containers
        run: |
          docker compose -f cypress/docker-compose.yml up -d
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          wait-on: 'http://localhost:5173'
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots/
          retention-days: 90
